### ISSUE TITLE
XML parsing error

### ISSUE THREAD

**Issue by msoida** [john-corcoran/backblaze-backup-checker#2]
Hi, first of all - thanks for making this nice script!

I run into XML parsing error:

```
INFO - Source path(s) '/Users/msoida/Downloads' will be compared against Backblaze log data in '/Library/Backblaze.bzpkg/bzdata'
INFO - Findings will be written to current working folder

Traceback (most recent call last):
  File "/Users/msoida/Downloads/backblaze-backup-checker-0.1.1/bbcheck.py", line 1102, in <module>
    main()
  File "/Users/msoida/Downloads/backblaze-backup-checker-0.1.1/bbcheck.py", line 1085, in main
    datetime_string=datetime_string,
  File "/Users/msoida/Downloads/backblaze-backup-checker-0.1.1/bbcheck.py", line 759, in check_backup
    exclude_rules = get_excludes(bzdata_folder_path)
  File "/Users/msoida/Downloads/backblaze-backup-checker-0.1.1/bbcheck.py", line 586, in get_excludes
    root = xml.etree.ElementTree.parse(exclude_file_path).getroot()
  File "/Users/msoida/.pyenv/versions/3.7.3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/Users/msoida/.pyenv/versions/3.7.3/lib/python3.7/xml/etree/ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: XML or text declaration not at start of entity: line 2, column 0
```

After some debugging, I found the problem to be in `/Library/Backblaze.bzpkg/bzdata/bzexcluderules_mandatory.xml` - this file had an empty line at the start. After removing this empty line, the script works great.

Now, I have no idea why this line was there. Since I have BackBlaze running for many years now, it's quite possible this happend due to some automatic file structure update many years ago. Whatever the reason is, it seems the BB client does not mind this extra line, and the Python XML parser does not like it.

While I expect that such problems are probably not too common, it would be nice to defend the rest of this awesome script against them ;)

PS: I'm using MacOS 10.15.7/Python 3.7.3, but I doubt it's relevant in this case.

**Comment by john-corcoran** [comment]
Thanks for the kind words and troubleshooting, much appreciated! This is hopefully fixed in https://github.com/john-corcoran/backblaze-backup-checker/blob/75e62e43d81f26933ca561226b4d538976857943/bbcheck.py - would you mind testing to see if it works? On confirmation I'll roll this into a new release.

**Comment by msoida** [comment]
I checked the fixed version - works great!
